// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXx_Himqo6nxpePClKFS6u35jgureJMs0',
    appId: '1:101146762541:web:aaaa279162086c3365c7a4',
    messagingSenderId: '101146762541',
    projectId: 'calling-app-practice',
    authDomain: 'calling-app-practice.firebaseapp.com',
    storageBucket: 'calling-app-practice.firebasestorage.app',
    measurementId: 'G-9NXM6VTVZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhur_7V2DpdE3j5u8EFebwvFNgwm0xXJ8',
    appId: '1:101146762541:android:97041a401d98167665c7a4',
    messagingSenderId: '101146762541',
    projectId: 'calling-app-practice',
    storageBucket: 'calling-app-practice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIt5IhK6RK3Kj8NG-gE--9hT2oYBTQ3Jk',
    appId: '1:101146762541:ios:b9760c4e43b81a7d65c7a4',
    messagingSenderId: '101146762541',
    projectId: 'calling-app-practice',
    storageBucket: 'calling-app-practice.firebasestorage.app',
    iosBundleId: 'me.nareshsharma.callingAppPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIt5IhK6RK3Kj8NG-gE--9hT2oYBTQ3Jk',
    appId: '1:101146762541:ios:b9760c4e43b81a7d65c7a4',
    messagingSenderId: '101146762541',
    projectId: 'calling-app-practice',
    storageBucket: 'calling-app-practice.firebasestorage.app',
    iosBundleId: 'me.nareshsharma.callingAppPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXx_Himqo6nxpePClKFS6u35jgureJMs0',
    appId: '1:101146762541:web:46f66259f764b1f465c7a4',
    messagingSenderId: '101146762541',
    projectId: 'calling-app-practice',
    authDomain: 'calling-app-practice.firebaseapp.com',
    storageBucket: 'calling-app-practice.firebasestorage.app',
    measurementId: 'G-MF9D8CHB8Z',
  );
}
